import type { Tool } from "@/lib/tools";

// A larger starter catalogue. Pricing is left as “Check pricing” because plans
// change often; each link goes to the product's own site for current details.
const entries: [string, string, string, string, string, string[]][] = [
  // AI assistants and chat
  ["claude", "Claude", "AI assistants", "Write, think, summarize, and work through complex questions with an AI assistant.", "claude.ai", ["Assistant", "Writing", "Research"]],
  ["gemini", "Google Gemini", "AI assistants", "Google’s AI assistant for brainstorming, learning, and getting things done.", "gemini.google.com", ["Assistant", "Research", "Google"]],
  ["microsoft-copilot", "Microsoft Copilot", "AI assistants", "An everyday AI assistant for answers, ideas, and help with work.", "copilot.microsoft.com", ["Assistant", "Productivity", "Microsoft"]],
  ["meta-ai", "Meta AI", "AI assistants", "Meta’s AI assistant for asking questions and creating images.", "meta.ai", ["Assistant", "Images", "Social"]],
  ["grok", "Grok", "AI assistants", "An AI assistant for questions, research, and creative work.", "grok.com", ["Assistant", "Research", "Chat"]],
  ["mistral-le-chat", "Le Chat by Mistral", "AI assistants", "A multilingual assistant for writing, research, and everyday tasks.", "chat.mistral.ai", ["Assistant", "Writing", "Research"]],
  ["deepseek", "DeepSeek", "AI assistants", "An AI chat assistant with general-purpose and reasoning models.", "chat.deepseek.com", ["Assistant", "Reasoning", "Chat"]],
  ["poe", "Poe", "AI assistants", "Explore and compare assistants and bots from different AI makers.", "poe.com", ["Assistant", "Chat", "Models"]],
  ["pi", "Pi", "AI assistants", "A conversational AI designed for supportive, natural-feeling chats.", "pi.ai", ["Assistant", "Conversation", "Chat"]],
  ["you-com", "You.com", "AI assistants", "Search the web and work with AI assistants in one place.", "you.com", ["Assistant", "Search", "Research"]],
  ["character-ai", "Character.AI", "AI assistants", "Chat with user-created characters and build your own conversations.", "character.ai", ["Chat", "Characters", "Creative"]],
  ["huggingchat", "HuggingChat", "AI assistants", "Try open models and chat with an AI assistant from Hugging Face.", "huggingface.co/chat", ["Assistant", "Open source", "Chat"]],
  ["phind", "Phind", "AI assistants", "An AI answer engine built to help developers research technical questions.", "phind.com", ["Assistant", "Coding", "Research"]],
  ["jan", "Jan", "AI assistants", "Run AI assistants locally on your computer with an open-source app.", "jan.ai", ["Assistant", "Local AI", "Open source"]],
  ["ollama", "Ollama", "AI assistants", "Download and run open AI models on your own computer.", "ollama.com", ["Local AI", "Developer", "Open source"]],
  // Writing and language
  ["jasper", "Jasper", "Writing", "Create and refine marketing content with a brand-focused AI writing platform.", "jasper.ai", ["Marketing", "Writing", "Brand"]],
  ["copy-ai", "Copy.ai", "Writing", "Draft marketing copy and automate common go-to-market workflows.", "copy.ai", ["Marketing", "Writing", "Business"]],
  ["writesonic", "Writesonic", "Writing", "Create marketing content and research topics with AI-powered tools.", "writesonic.com", ["Writing", "SEO", "Marketing"]],
  ["rytr", "Rytr", "Writing", "Draft and improve short-form writing for work and personal projects.", "rytr.me", ["Writing", "Copywriting", "Ideas"]],
  ["sudowrite", "Sudowrite", "Writing", "A creative writing companion for fiction writers and storytellers.", "sudowrite.com", ["Fiction", "Writing", "Storytelling"]],
  ["wordtune", "Wordtune", "Writing", "Rewrite sentences, adjust tone, and make writing clearer.", "wordtune.com", ["Editing", "Writing", "Grammar"]],
  ["quillbot", "QuillBot", "Writing", "Paraphrase, check grammar, and summarize text in one writing workspace.", "quillbot.com", ["Writing", "Editing", "Summaries"]],
  ["anyword", "Anyword", "Writing", "Draft and optimize marketing copy for different audiences.", "anyword.com", ["Marketing", "Copywriting", "Writing"]],
  ["writer", "Writer", "Writing", "Create on-brand business content with controls for teams.", "writer.com", ["Business", "Writing", "Brand"]],
  ["hyperwrite", "HyperWrite", "Writing", "Get help drafting, rewriting, and researching from a browser-based assistant.", "hyperwriteai.com", ["Writing", "Research", "Assistant"]],
  ["deepl-write", "DeepL Write", "Writing", "Improve grammar, phrasing, and tone while you write.", "deepl.com/write", ["Editing", "Writing", "Translation"]],
  ["languagetool", "LanguageTool", "Writing", "Check spelling, grammar, and style in many languages.", "languagetool.org", ["Grammar", "Editing", "Writing"]],
  ["novelai", "NovelAI", "Writing", "Explore AI-assisted storytelling and illustration for creative projects.", "novelai.net", ["Fiction", "Writing", "Images"]],
  // Image generation and editing
  ["adobe-firefly", "Adobe Firefly", "Image generation", "Generate and edit images, designs, and creative assets with Adobe AI.", "firefly.adobe.com", ["Images", "Design", "Editing"]],
  ["leonardo-ai", "Leonardo AI", "Image generation", "Generate and refine images for art, games, and creative projects.", "leonardo.ai", ["Images", "Art", "Design"]],
  ["recraft", "Recraft", "Image generation", "Create illustrations, vectors, icons, and image assets with AI.", "recraft.ai", ["Images", "Vector", "Design"]],
  ["krea", "Krea", "Image generation", "Explore real-time image generation, enhancement, and visual editing.", "krea.ai", ["Images", "Design", "Editing"]],
  ["playground-ai", "Playground", "Image generation", "Create and edit images in a browser-based AI design canvas.", "playground.com", ["Images", "Design", "Editing"]],
  ["freepik-ai", "Freepik AI", "Image generation", "Generate images and creative assets inside the Freepik ecosystem.", "freepik.com/ai", ["Images", "Design", "Assets"]],
  ["nightcafe", "NightCafe", "Image generation", "Explore AI image generation styles and share creations with a community.", "nightcafe.studio", ["Images", "Art", "Community"]],
  ["dreamstudio", "DreamStudio", "Image generation", "Create images using Stability AI’s image-generation models.", "dreamstudio.ai", ["Images", "Art", "Generation"]],
  ["getimg", "getimg.ai", "Image generation", "Generate, edit, and expand images with online AI tools.", "getimg.ai", ["Images", "Editing", "Design"]],
  ["photoroom", "PhotoRoom", "Image generation", "Make product photos, remove backgrounds, and create marketing images.", "photoroom.com", ["Product photos", "Editing", "Images"]],
  ["clipdrop", "Clipdrop", "Image generation", "A collection of image cleanup, relighting, and generation tools.", "clipdrop.co", ["Images", "Editing", "Design"]],
  ["remove-bg", "remove.bg", "Image generation", "Remove image backgrounds automatically in a few clicks.", "remove.bg", ["Editing", "Background removal", "Images"]],
  ["magnific", "Magnific AI", "Image generation", "Upscale and add detail to images with AI-powered enhancement.", "magnific.ai", ["Upscaling", "Images", "Editing"]],
  // Video creation and editing
  ["sora", "Sora", "Video", "Create and edit short videos from text and image prompts.", "sora.com", ["Video", "Generation", "Creative"]],
  ["kling-ai", "Kling AI", "Video", "Generate videos and animate images with text prompts.", "klingai.com", ["Video", "Generation", "Creative"]],
  ["luma-dream-machine", "Luma Dream Machine", "Video", "Create cinematic video clips from text and image ideas.", "lumalabs.ai/dream-machine", ["Video", "Generation", "Creative"]],
  ["pika", "Pika", "Video", "Turn visual ideas into short videos and experiment with creative effects.", "pika.art", ["Video", "Effects", "Creative"]],
  ["heygen", "HeyGen", "Video", "Make presenter-led videos with AI avatars and voice options.", "heygen.com", ["Video", "Avatars", "Business"]],
  ["synthesia", "Synthesia", "Video", "Create training and business videos with digital presenters.", "synthesia.io", ["Video", "Training", "Business"]],
  ["invideo-ai", "InVideo AI", "Video", "Create and edit social and marketing videos with AI assistance.", "invideo.io", ["Video", "Marketing", "Editing"]],
  ["veed", "VEED", "Video", "Edit videos online with captions, cleanup, and AI-assisted tools.", "veed.io", ["Video", "Editing", "Captions"]],
  ["opusclip", "OpusClip", "Video", "Find shareable short clips from longer video content.", "opus.pro", ["Video", "Clips", "Social"]],
  ["captions", "Captions", "Video", "Edit talking videos, create captions, and produce social content.", "captions.ai", ["Video", "Captions", "Editing"]],
  ["descript", "Descript", "Video", "Edit audio and video by editing the words in their transcripts.", "descript.com", ["Video", "Audio", "Editing"]],
  ["wisecut", "Wisecut", "Video", "Speed up talking-video edits with automatic cuts and captions.", "wisecut.video", ["Video", "Editing", "Captions"]],
  // Audio and music
  ["udio", "Udio", "Audio", "Generate and explore original music from written prompts.", "udio.com", ["Music", "Audio", "Generation"]],
  ["aiva", "AIVA", "Audio", "Compose original music for videos, games, and creative projects.", "aiva.ai", ["Music", "Composition", "Audio"]],
  ["soundraw", "SOUNDRAW", "Audio", "Make and customize royalty-free background music for projects.", "soundraw.io", ["Music", "Audio", "Creator"]],
  ["murf", "Murf AI", "Audio", "Create voiceovers for presentations, videos, and learning content.", "murf.ai", ["Voice", "Audio", "Voiceover"]],
  ["playht", "PlayHT", "Audio", "Generate voiceovers and build text-to-speech experiences.", "play.ht", ["Voice", "Audio", "Text to speech"]],
  ["adobe-podcast", "Adobe Podcast", "Audio", "Enhance spoken audio and record clear remote conversations.", "podcast.adobe.com", ["Audio", "Podcast", "Editing"]],
  ["krisp", "Krisp", "Audio", "Reduce background noise and improve clarity on calls.", "krisp.ai", ["Audio", "Meetings", "Noise removal"]],
  ["fish-audio", "Fish Audio", "Audio", "Create expressive speech and voice content with AI audio tools.", "fish.audio", ["Voice", "Audio", "Text to speech"]],
  ["lalal-ai", "LALAL.AI", "Audio", "Separate vocals and instruments from audio and video files.", "lalal.ai", ["Audio", "Music", "Editing"]],
  ["mubert", "Mubert", "Audio", "Generate soundtracks and royalty-free music for digital content.", "mubert.com", ["Music", "Audio", "Creator"]],
  // Coding and app building
  ["windsurf", "Windsurf", "Coding", "An AI-powered coding editor for building and understanding software.", "windsurf.com", ["Code", "Developer", "Editor"]],
  ["replit", "Replit", "Coding", "Build, run, and share apps in a browser with AI coding help.", "replit.com", ["Code", "Apps", "Developer"]],
  ["lovable", "Lovable", "Coding", "Turn written ideas into working web app prototypes.", "lovable.dev", ["Apps", "No-code", "Developer"]],
  ["bolt", "Bolt.new", "Coding", "Prototype and run full-stack web apps from a browser prompt.", "bolt.new", ["Apps", "Developer", "No-code"]],
  ["v0", "v0 by Vercel", "Coding", "Generate user interfaces and web app code from descriptions.", "v0.dev", ["Code", "Design", "Developer"]],
  ["devin", "Devin", "Coding", "An AI software engineering agent for assisted development tasks.", "devin.ai", ["Code", "Developer", "Agent"]],
  ["tabnine", "Tabnine", "Coding", "Get AI code suggestions and assistance in your development environment.", "tabnine.com", ["Code", "Developer", "Editor"]],
  ["sourcegraph-cody", "Cody", "Coding", "Ask questions and get coding help grounded in your codebase.", "sourcegraph.com/cody", ["Code", "Developer", "Search"]],
  ["continue", "Continue", "Coding", "An open-source AI coding assistant that works with your editor and models.", "continue.dev", ["Code", "Developer", "Open source"]],
  ["zed", "Zed", "Coding", "A fast code editor with built-in AI collaboration features.", "zed.dev", ["Code", "Developer", "Editor"]],
  ["boltai", "BoltAI", "Coding", "A Mac AI app for working with assistants and coding workflows.", "boltai.com", ["Code", "Assistant", "Mac"]],
  ["blackbox-ai", "Blackbox AI", "Coding", "Search, understand, and generate code with AI assistance.", "blackbox.ai", ["Code", "Developer", "Search"]],
  ["qodo", "Qodo", "Coding", "Generate and review code with AI tools for development teams.", "qodo.ai", ["Code", "Testing", "Developer"]],
  // Design and presentations
  ["figma-ai", "Figma AI", "Design", "Explore AI-assisted design and prototyping features in Figma.", "figma.com/ai", ["Design", "Prototype", "Collaboration"]],
  ["uizard", "Uizard", "Design", "Turn product ideas and rough sketches into editable interface mockups.", "uizard.io", ["Design", "Prototyping", "Apps"]],
  ["framer-ai", "Framer AI", "Design", "Create and publish polished websites with AI-assisted design tools.", "framer.com/ai", ["Design", "Websites", "No-code"]],
  ["relume", "Relume", "Design", "Plan website pages and generate starting points for design and copy.", "relume.io", ["Design", "Websites", "Wireframes"]],
  ["gamma", "Gamma", "Presentations", "Create presentations, web pages, and visual documents from an outline.", "gamma.app", ["Presentations", "Documents", "Design"]],
  ["beautiful-ai", "Beautiful.ai", "Presentations", "Build and format professional presentations with smart layouts.", "beautiful.ai", ["Presentations", "Design", "Business"]],
  ["tome", "Tome", "Presentations", "Create and share visual narratives and presentation-style stories.", "tome.app", ["Presentations", "Storytelling", "Design"]],
  ["pitch", "Pitch", "Presentations", "Design and collaborate on polished team presentations.", "pitch.com", ["Presentations", "Business", "Collaboration"]],
  ["plus-ai", "Plus AI", "Presentations", "Create and edit presentations inside Google Slides and PowerPoint.", "plusai.com", ["Presentations", "Google Slides", "PowerPoint"]],
  ["slidesai", "SlidesAI", "Presentations", "Turn written notes into a presentation draft.", "slidesai.io", ["Presentations", "Google Slides", "Writing"]],
  ["presentations-ai", "Presentations.AI", "Presentations", "Draft business presentations and pitch decks from a prompt.", "presentations.ai", ["Presentations", "Business", "Design"]],
  ["napkin-ai", "Napkin AI", "Design", "Turn written ideas into simple diagrams and visual explanations.", "napkin.ai", ["Diagrams", "Design", "Documents"]],
  ["visily", "Visily", "Design", "Build interface wireframes and prototypes with AI-assisted workflows.", "visily.ai", ["Design", "Prototyping", "Apps"]],
  // Research and learning
  ["notebooklm", "NotebookLM", "Research", "Ask questions and create summaries from your own source material.", "notebooklm.google.com", ["Research", "Notes", "Sources"]],
  ["elicit", "Elicit", "Research", "Find and organize academic papers for research questions.", "elicit.com", ["Research", "Academic", "Papers"]],
  ["consensus", "Consensus", "Research", "Explore research-backed answers from published scientific papers.", "consensus.app", ["Research", "Academic", "Papers"]],
  ["scite", "Scite", "Research", "Explore how research papers are cited and discussed by later studies.", "scite.ai", ["Research", "Academic", "Citations"]],
  ["scispace", "SciSpace", "Research", "Read and understand scientific papers with research assistance.", "scispace.com", ["Research", "Academic", "Papers"]],
  ["connected-papers", "Connected Papers", "Research", "Discover related academic papers from a research starting point.", "connectedpapers.com", ["Research", "Academic", "Discovery"]],
  ["wolframalpha", "Wolfram|Alpha", "Research", "Compute answers and explore structured knowledge across many subjects.", "wolframalpha.com", ["Research", "Math", "Learning"]],
  ["researchrabbit", "ResearchRabbit", "Research", "Map related research papers and follow a topic’s literature.", "researchrabbit.ai", ["Research", "Academic", "Discovery"]],
  ["khanmigo", "Khanmigo", "Education", "Practice learning with an AI tutor from Khan Academy.", "khanacademy.org/khan-labs", ["Learning", "Tutor", "Education"]],
  ["quizlet", "Quizlet", "Education", "Study with flashcards and AI-assisted practice tools.", "quizlet.com", ["Learning", "Flashcards", "Education"]],
  ["duolingo-max", "Duolingo", "Education", "Practice a language with lessons and AI features in supported plans.", "duolingo.com", ["Learning", "Language", "Education"]],
  ["magicschool", "MagicSchool", "Education", "Explore AI tools designed for teachers and classroom workflows.", "magicschool.ai", ["Education", "Teachers", "Learning"]],
  ["brisk-teaching", "Brisk Teaching", "Education", "Create and adapt teaching materials with browser-based AI tools.", "briskteaching.com", ["Education", "Teachers", "Writing"]],
  // Productivity, automation, and meetings
  ["clickup-ai", "ClickUp AI", "Productivity", "Plan projects, summarize work, and write with AI in ClickUp.", "clickup.com/ai", ["Productivity", "Projects", "Teams"]],
  ["asana-ai", "Asana AI", "Productivity", "Coordinate projects and use AI features in Asana work management.", "asana.com/product/ai", ["Productivity", "Projects", "Teams"]],
  ["zapier", "Zapier", "Automation", "Connect apps and automate repeatable workflows with no-code tools.", "zapier.com", ["Automation", "No-code", "Integrations"]],
  ["make", "Make", "Automation", "Build visual automations that connect apps and online services.", "make.com", ["Automation", "No-code", "Integrations"]],
  ["n8n", "n8n", "Automation", "Create flexible workflow automations with hosted or self-hosted options.", "n8n.io", ["Automation", "Developer", "Open source"]],
  ["airtable-ai", "Airtable AI", "Productivity", "Organize projects and data with AI features in Airtable.", "airtable.com/ai", ["Productivity", "Data", "Teams"]],
  ["coda-ai", "Coda AI", "Productivity", "Bring documents, tables, and AI-assisted workflows together.", "coda.io/product/ai", ["Productivity", "Documents", "Teams"]],
  ["motion", "Motion", "Productivity", "Plan tasks and calendars with an AI-assisted daily schedule.", "usemotion.com", ["Productivity", "Calendar", "Planning"]],
  ["reclaim", "Reclaim AI", "Productivity", "Protect focus time and schedule habits around your calendar.", "reclaim.ai", ["Productivity", "Calendar", "Planning"]],
  ["taskade", "Taskade", "Productivity", "Plan projects, collaborate, and create AI-powered team workflows.", "taskade.com", ["Productivity", "Projects", "Teams"]],
  ["fireflies", "Fireflies.ai", "Meeting assistants", "Record, transcribe, and search key points from online meetings.", "fireflies.ai", ["Meetings", "Transcription", "Notes"]],
  ["otter", "Otter.ai", "Meeting assistants", "Transcribe conversations and create searchable meeting notes.", "otter.ai", ["Meetings", "Transcription", "Notes"]],
  ["fathom", "Fathom", "Meeting assistants", "Record and summarize online meetings for easier follow-up.", "fathom.video", ["Meetings", "Notes", "Summaries"]],
  ["tldv", "tl;dv", "Meeting assistants", "Capture meeting recordings, transcripts, and shareable highlights.", "tldv.io", ["Meetings", "Transcription", "Highlights"]],
  ["read-ai", "Read AI", "Meeting assistants", "Get meeting summaries and conversation insights from calls.", "read.ai", ["Meetings", "Summaries", "Productivity"]],
  ["granola", "Granola", "Meeting assistants", "Turn meeting notes into a useful, searchable record.", "granola.ai", ["Meetings", "Notes", "Productivity"]],
  ["turboscribe", "TurboScribe", "Transcription", "Transcribe audio and video recordings into editable text.", "turboscribe.ai", ["Transcription", "Audio", "Notes"]],
  ["sonix", "Sonix", "Transcription", "Transcribe and subtitle audio and video in multiple languages.", "sonix.ai", ["Transcription", "Captions", "Audio"]],
  ["whisper", "Whisper", "Transcription", "OpenAI’s speech-recognition model for transcribing audio.", "openai.com/research/whisper", ["Transcription", "Developer", "Audio"]],
  // Marketing, SEO, analytics, and customer support
  ["hubspot-ai", "HubSpot AI", "Marketing", "Use AI-assisted tools for marketing, sales, and customer support work.", "hubspot.com/artificial-intelligence", ["Marketing", "Business", "CRM"]],
  ["semrush", "Semrush", "Marketing", "Research keywords and improve search visibility with SEO tools.", "semrush.com", ["SEO", "Marketing", "Research"]],
  ["surfer", "Surfer", "Marketing", "Plan and optimize content for search with SEO workflows.", "surferseo.com", ["SEO", "Writing", "Marketing"]],
  ["frase", "Frase", "Marketing", "Research search topics and create content briefs and drafts.", "frase.io", ["SEO", "Writing", "Research"]],
  ["marketmuse", "marketmuse", "Marketing", "Plan content topics and research opportunities for SEO teams.", "marketmuse.com", ["SEO", "Research", "Marketing"]],
  ["predis-ai", "Predis.ai", "Marketing", "Create social media posts and creative concepts with AI assistance.", "predis.ai", ["Social", "Marketing", "Design"]],
  ["ocoya", "Ocoya", "Marketing", "Plan and create social media content in a marketing workspace.", "ocoya.com", ["Social", "Marketing", "Writing"]],
  ["julius-ai", "Julius AI", "Data & analytics", "Explore spreadsheets and datasets with a conversational analysis tool.", "julius.ai", ["Data", "Analytics", "Research"]],
  ["akkio", "Akkio", "Data & analytics", "Build and explore predictive analytics workflows with AI.", "akkio.com", ["Data", "Analytics", "Business"]],
  ["obviously-ai", "Obviously AI", "Data & analytics", "Create no-code predictions from business data.", "obviously.ai", ["Data", "Analytics", "No-code"]],
  ["tableau-pulse", "Tableau", "Data & analytics", "Explore data dashboards and AI-assisted business insights.", "tableau.com", ["Data", "Analytics", "Business"]],
  ["power-bi", "Power BI", "Data & analytics", "Build reports and explore data with Microsoft's analytics platform.", "powerbi.microsoft.com", ["Data", "Analytics", "Business"]],
  ["intercom-fin", "Intercom Fin", "Customer support", "Automate customer support answers using your help content.", "intercom.com/fin", ["Support", "Customer service", "Business"]],
  ["zendesk-ai", "Zendesk AI", "Customer support", "Support service teams with AI-assisted customer conversations.", "zendesk.com/ai", ["Support", "Customer service", "Business"]],
  ["tidio-lyro", "Tidio Lyro", "Customer support", "Answer common customer questions with an AI support assistant.", "tidio.com/lyro", ["Support", "Chatbot", "Customer service"]],
  ["gorgias-ai", "Gorgias", "Customer support", "Help ecommerce support teams respond to customer messages.", "gorgias.com", ["Support", "Ecommerce", "Customer service"]],
];

const categoryColors: Record<string, string> = {
  "AI assistants": "mint", Writing: "blue", "Image generation": "pink", Video: "violet", Audio: "orange", Coding: "cream", Design: "blue", Presentations: "violet", Research: "mint", Education: "orange", Productivity: "cream", Automation: "mint", "Meeting assistants": "blue", Transcription: "orange", Marketing: "pink", "Data & analytics": "violet", "Customer support": "cream",
};

export const moreTools: Tool[] = entries.map(([slug, name, category, description, website, tags]) => ({
  slug,
  name,
  category,
  description,
  price: "Check pricing",
  icon: name.replace(/[^A-Za-z0-9 ]/g, "").split(/\s+/).map((part) => part[0]).join("").slice(0, 2),
  color: categoryColors[category] || "mint",
  website: website.startsWith("http") ? `https://${website}` : `https://${website}`,
  tags,
}));
